[project]
site_name = "老罗投资"
site_description = "老罗投资 / 知行合一 日拱一卒 投资人生"
site_author = "laoluotouzi"
site_dir = "dist"
site_url = "http://localhost:8000/"
dev_addr = "localhost:8000"
copyright = "Copyright &copy; 2025 老罗投资 / 知行合一 日拱一卒 投资人生"

docs_dir = "docs"
extra_css = ["assets/extra.css"]
extra_javascript = ["assets/extra.js"]

[project.theme]
variant = "material"
custom_dir = "overrides"
favicon = "assets/images/favicon.ico"
language = "zh"
features = []

[[project.theme.palette]]
scheme = "default"
#toggle.icon = "lucide/sun"
#toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

#[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"

#[project.theme.icon]
#logo = "assets/images/logo.png"
#repo = "lucide/smile"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/laoluotouzi"


